version: "3.8"

services: 
  #################################################
  #
  # Smartcontract
  #
  #################################################
  xdex-smartcontracts:
    build:
      context: ./smartcontracts
    container_name: "xdex-smartcontracts"
    volumes:
      - type: bind
        source: ./smartcontracts
        target: /home/node/app
      - /home/node/app/node_modules
    networks:
      - net
    entrypoint: sh
    command: '-c "sleep 1d"'
    env_file:
      - ./smartcontracts/.env
  #################################################
  #
  # Bridge that is between different blockchains
  #
  #################################################
  ara-mvp:
    build:
      context: ./ara-mvp
    container_name: "ara-mvp"
    volumes:
      - type: bind
        source: ./ara-mvp
        target: /home/node/app
      - /home/node/app/node_modules
    env_file:
      - ./ara-mvp/.env
    networks:
      - net
    entrypoint: sh
    command: '-c "sleep 1d"'
    links:
      - kafka
    ports:
      - "3010:3010"
      - "3020:3020"
  eventeum:        
    image: eventeum/eventeum:latest
    container_name: "eventeum"
    ports:
    - "8060:8060"
    depends_on:
      - mongodb
      - kafka
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      ETHEREUM_NODE_BLOCKSTRATEGY: PUBSUB
      # ETHEREUM_NODE_URL: <your default Blockchain node URL>
      ZOOKEEPER_ADDRESS: zookeeper:2181
      KAFKA_ADDRESSES: kafka:19092
    volumes:
      - type: bind
        source: ./ara-mvp/application.yml
        target: /application.yml
    env_file:
      - ./ara-mvp/.env
    networks:
      - net
  mongodb:
    container_name: "eventeum-database"
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /mongodb/data/db:/data/db
    networks:
      - net
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.1-1
    container_name: "eventeum-message-topics"
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - net
  kafka:
    image: confluentinc/cp-kafka:5.0.1-1
    container_name: "eventeum-message-broadcaster"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - net
volumes: 
  db-data:
networks:
  net:
