ethereum:
  sync:
    batchSize: 1000
  nodes:
  - name: default
    url: ${ETHEREUM_NODE_URL:http://localhost:8545}
    blockStrategy: PUBSUB
    syncingThreshold: 100
    healthcheckInterval: 5000
    maxBlocksToSync: 0
  - name: rinkeby
    blockStrategy: PUBSUB
    url: wss://rinkeby.infura.io/ws/v3/23559084cbf347d1b948f225c88a6fa0
    pollInterval: 1000
    maxIdleConnections: 10
    keepAliveDuration: 15000
    connectionTimeout: 7000
    readTimeout: 35000
    healthcheckInterval: 3000
    addTransactionRevertReason: true
    numBlocksToWait: 1
    numBlocksToWaitBeforeInvalidating: 1
    numBlocksToWaitForMissingTx: 1
  # - name: bscTestnet
  #   blockStrategy: PUBSUB
  #   url: https://data-seed-prebsc-1-s1.binance.org:8545
  #   pollInterval: 1000
  #   maxIdleConnections: 10
  #   keepAliveDuration: 15000
  #   connectionTimeout: 7000
  #   readTimeout: 35000
  #   healthcheckInterval: 3000
  #   addTransactionRevertReason: true
  #   numBlocksToWait: 1
  #   numBlocksToWaitBeforeInvalidating: 1
  #   numBlocksToWaitForMissingTx: 1
eventFilters:
  - id: RinkebyBscTestnetPairCreated
    node: rinkeby
    contractAddress: "0x1fbC435F5Ce41aF6E4988be77453b6383a3d3b5b"
    eventSpecification:
      eventName: PairCreated
      indexedParameterDefinitions:
        - position: 0
          type: ADDRESS
        - position: 1
          type: ADDRESS
        - position: 2
          type: ADDRESS
      nonIndexedParameterDefinitions:
        - position: 3
          type: UINT256
    correlationId:
      type: INDEXED_PARAMETER
      index: 0
  # - id: BscTestnetRinkebyPairCreated
  #   node: bscTestnet
  #   contractAddress: "0xCC084E9962eFc1f35fD18423Dc2424a0A0324f18"
  #   eventSpecification:
  #     eventName: PairCreated
  #     indexedParameterDefinitions:
  #       - position: 0
  #         type: ADDRESS
  #       - position: 1
  #         type: ADDRESS
  #       - position: 2
  #         type: ADDRESS
  #     nonIndexedParameterDefinitions:
  #       - position: 3
  #         type: UINT256
  #   correlationId:
  #     type: INDEXED_PARAMETER
  #     index: 0
